package com.harikiran.pgmgmt.model;

import java.time.Instant;
import java.util.Date;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.CompoundIndex;
import org.springframework.data.mongodb.core.mapping.Document;

import lombok.Data;

/**
 * Time-series snapshot capturing meal preference distribution for a given day
 * and meal number.
 *
 * <p>
 * The combination of {@link #statsDate} and {@link #mealNo} is unique to avoid
 * duplicate snapshots. Records are generated by
 * {@link com.harikiran.pgmgmt.service.MealStatsScheduler} and consumed by the
 * reporting dashboard.
 * </p>
 */
@Data
@Document(collection = "meal_stats")
@CompoundIndex(name = "stats_date_meal_idx", def = "{ 'statsDate': 1, 'mealNo': 1 }", unique = true)
public class MealStats {

	@Id
	/**
	 * Unique identifier generated by MongoDB.
	 */
	private String id;

	/**
	 * Date for which the meal snapshot was captured.
	 */
	private Date statsDate;

	/**
	 * Meal number (1 = breakfast, 2 = lunch, 3 = dinner) captured by the
	 * scheduler.
	 */
	private int mealNo;

	/**
	 * Total number of active tenants at capture time.
	 */
	private long totalCount;

	/**
	 * Count of tenants preferring vegetarian meals.
	 */
	private long vegCount;

	/**
	 * Count of tenants preferring non-vegetarian meals.
	 */
	private long nonVegCount;

	/**
	 * Timestamp indicating when the snapshot was created.
	 */
	private Instant capturedAt;

	/**
	 * Default constructor required by MongoDB drivers.
	 */
	public MealStats() {
	}

	/**
	 * Creates a snapshot stub for the supplied date and meal number.
	 *
	 * @param statsDate day of the snapshot
	 * @param mealNo    meal slot number in the day
	 */
	public MealStats(Date statsDate, int mealNo) {
		this.statsDate = statsDate;
		this.mealNo = mealNo;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Date getStatsDate() {
		return statsDate;
	}

	public void setStatsDate(Date statsDate) {
		this.statsDate = statsDate;
	}

	public int getMealNo() {
		return mealNo;
	}

	public void setMealNo(int mealNo) {
		this.mealNo = mealNo;
	}

	public long getTotalCount() {
		return totalCount;
	}

	public void setTotalCount(long totalCount) {
		this.totalCount = totalCount;
	}

	public long getVegCount() {
		return vegCount;
	}

	public void setVegCount(long vegCount) {
		this.vegCount = vegCount;
	}

	public long getNonVegCount() {
		return nonVegCount;
	}

	public void setNonVegCount(long nonVegCount) {
		this.nonVegCount = nonVegCount;
	}

	public Instant getCapturedAt() {
		return capturedAt;
	}

	public void setCapturedAt(Instant capturedAt) {
		this.capturedAt = capturedAt;
	}

}
