package com.harikiran.pgmgmt.model;

import java.util.List;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import lombok.Data;

/**
 * MongoDB document describing a bed room available for tenant allocation.
 *
 * <p>
 * The document captures capacity, location details and a cached allocation
 * count that allows the frontend to render occupancy summaries without
 * additional aggregation queries.
 * </p>
 */
@Data
@Document(collection = "rooms")
public class Room {
	/**
	 * Unique identifier generated by MongoDB.
	 */
	@Id
	private String id;

	/**
	 * Human readable room number displayed to tenants.
	 */
	private String roomNo;

	/**
	 * Maximum occupancy for the room.
	 */
	private int capacity;

	/**
	 * Floor label used for grouping in dashboards.
	 */
	private String floorNo;

	/**
	 * Optional administrative notes about the room.
	 */
	private String comments;

	/**
	 * Cached number of tenants currently assigned.
	 */
	private int allocatedCount;

	/**
	 * List of tenant identifiers assigned to the room; used for coordination and
	 * validation logic.
	 */
	private List<String> tenantIds;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getRoomNo() {
		return roomNo;
	}

	public void setRoomNo(String roomNo) {
		this.roomNo = roomNo;
	}

	public int getCapacity() {
		return capacity;
	}

	public void setCapacity(int capacity) {
		this.capacity = capacity;
	}

	public String getFloorNo() {
		return floorNo;
	}

	public void setFloorNo(String floorNo) {
		this.floorNo = floorNo;
	}

	public String getComments() {
		return comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public int getAllocatedCount() {
		return allocatedCount;
	}

	public void setAllocatedCount(int allocatedCount) {
		this.allocatedCount = allocatedCount;
	}

	public List<String> getTenantIds() {
		return tenantIds;
	}

	public void setTenantIds(List<String> tenantIds) {
		this.tenantIds = tenantIds;
	}

}
