services:
  - type: web
    name: pg-mgmt-backend
    env: docker
    dockerfilePath: ./pg-mgmt-backend/Dockerfile
    dockerContext: ./pg-mgmt-backend
    envVars:
      - key: SPRING_DATA_MONGODB_URI
        sync: false  # Set manually in dashboard
      - key: JWT_SECRET
        generateValue: true
        sync: false
      - key: GOOGLE_OAUTH_CLIENT_ID
        sync: false
      - key: APP_CORS_ALLOWED_ORIGINS
        value: https://pg-mgmt-frontend.onrender.com
    healthCheckPath: /actuator/health